import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Nunito } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

import { Toaster } from "react-hot-toast";

import { AuthProvider } from "@/providers/auth-provider";
import { QueryProvider } from "@/providers/query-provider";
import { CookieProvider } from "@/providers/cookie-provider";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = (await cookies()).get("token")?.value || "";

  return (
    <AuthProvider>
      <CookieProvider cookie={token}>
        <html lang="en">
          <body className={cn(font.className, "antialiased")}>
            <QueryProvider>
              {children}
              <Toaster />
            </QueryProvider>
          </body>
        </html>
      </CookieProvider>
    </AuthProvider>
  );
}
